---
- name: Setup clients
  hosts: clients
  gather_facts: no

  vars:
    target_name: "client"

  roles:
    - setup

- name: Setup servers
  hosts: servers
  gather_facts: no

  vars:
    target_name: "server"

  roles:
    - setup
